package main

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/schemes/ckks"
	"gonum.org/v1/gonum/mat"

	"govempc/core"
	"govempc/examples"
	"govempc/internal/ckksconfig"
	"govempc/solvers"
)

func main() {
	// Load config
	cfgPath := filepath.Join("output", "ckks_config.json")
	cfg, _ := ckksconfig.Load(cfgPath)

	m, l, g := cfg.Mass, cfg.Length, cfg.Gravity
	dt := cfg.DT
	N := cfg.N
	Ac, Bc := examples.LinearizedInvertedPendulumContinuous(m, l, g)
	A, B := examples.Discretize(Ac, Bc, dt)

	// Build the condensed MPC problem.
	n, _ := A.Dims()
	_, mIn := B.Dims()
	Q := diagDense(cfg.QDiag)
	R := diagDense(cfg.RDiag)
	Qf := mat.NewDense(n, n, nil)
	Qf.Scale(cfg.QfScale, Q)

	// Constraints
	thetaMax := cfg.ThetaMax
	omegaMax := cfg.OmegaMax
	uMax := cfg.UMax
	xBound := []float64{thetaMax, omegaMax}
	Gx := stackIdentity(n)
	hx := append(append([]float64{}, xBound...), xBound...)
	Gu := stackIdentity(mIn)
	hu := []float64{uMax, uMax}

	// Compact QP representation
	mpc := core.NewMPCProblem(A, B, Q, R, Qf, N)
	G, hOfX0 := mpc.BuildConstraintMatrices(Gx, hx, Gu, hu)
	penalty := core.NewConstraintPenalty(G, hOfX0, "indicator")

	// Variational parameters
	chebOrder := cfg.ChebOrder
	chebBound := cfg.ChebBound
	chebEta := cfg.ChebEta
	sigma0 := cfg.Sigma0
	Sigma0 := scaledIdentity(mpc.StackedInputDim(), sigma0*sigma0)
	lambdaParam := cfg.LambdaParam
	variational := core.NewVariationalMPC(mpc, penalty, lambdaParam, Sigma0)

	// Cache sizes
	K := cfg.K
	T := cfg.T
	nWorkers := cfg.NWorkers
	if nWorkers <= 0 {
		nWorkers = 1
	}
	if K%nWorkers != 0 {
		panic("K must be divisible by nWorkers in output/ckks_config.json")
	}

	LU := variational.LU
	var Gamma mat.Dense
	Gamma.Mul(penalty.G, LU)

	// Load offline cache generated by Algorithm 1
	cacheDir := filepath.Join("output", "ckks_cache")
	cryptoDir := filepath.Join(cacheDir, "crypto")
	params, sk, pk, rlk := loadCrypto(cryptoDir)

	Nm := mpc.StackedInputDim()
	dim := Nm
	rG, _ := Gamma.Dims()
	p := rG

	slots := params.MaxSlots()
	if dim > slots || p > slots {
		panic("dim or p exceeds CKKS slots")
	}

	slotWidth := maxInt(dim, p)
	KChunk := K / nWorkers
	if KChunk < 1 {
		panic("K_chunk must be positive")
	}
	if slots < slotWidth*KChunk {
		panic("not enough slots to process K_chunk samples; increase logN or reduce K or nWorkers")
	}

	// Configure CKKS
	logW := make([]float64, K)
	kgen := ckks.NewKeyGenerator(params)
	rotations := collectOnlineRotations(KChunk, dim, p, slots)
	gks := make([]*rlwe.GaloisKey, 0, len(rotations))
	for _, rot := range rotations {
		gks = append(gks, kgen.GenGaloisKeyNew(params.GaloisElementForRotation(rot), sk))
	}
	evalKeys := rlwe.NewMemEvaluationKeySet(rlk, gks...)

	chebCoeffs := solvers.ChebyshevReLUCoeffs(chebOrder, chebBound, 0)
	polyT := chebToPower(chebCoeffs)
	polyZ := scalePoly(polyT, chebBound)

	// Set threshold as the value of Chebyshev polynomial at origin
	deltaL := evalPolyReal(polyZ, 0.0)
	tauS := float64(p) * deltaL

	workers := make([]*onlineWorker, nWorkers)
	for w := 0; w < nWorkers; w++ {
		workers[w] = newOnlineWorker(
			workerCacheDir(cacheDir, w, nWorkers),
			KChunk,
			dim,
			p,
			slots,
			params,
			sk,
			evalKeys,
			polyZ,
			tauS,
		)
	}
	muEncryptor := newInputEncryptor(params, pk, slots)
	bEncryptor := newInputEncryptor(params, pk, slots)

	// Run the online encrypted controller over the closed-loop rollout.
	x0 := cfg.X0
	x := make([]float64, len(x0))
	copy(x, x0)

	xs := mat.NewDense(T+1, n, nil)
	us := mat.NewDense(T, mIn, nil)
	for j := 0; j < n; j++ {
		xs.Set(0, j, x[j])
	}

	controlMsSeries := make([]float64, T)
	Uhat := make([]float64, Nm)
	bar := newProgressBar("ckks_online", T)

	for t := 0; t < T; t++ {
		iterStart := time.Now()

		// 1. Client side
		mU := computeMU(variational, x)
		b := computeB(penalty, mU, x)
		ctMU := muEncryptor.EncryptTiled(mU, dim, KChunk, workers[0].cache.Load("ct_Lu", t).Level())
		ctB := bEncryptor.EncryptTiled(b, p, KChunk, workers[0].cache.Load("ct_Gamma", t).Level())

		var wg sync.WaitGroup
		errCh := make(chan error, nWorkers)
		// 2. Cloud side Parllelized execution of Protocol 2
		for _, worker := range workers {
			worker := worker
			wg.Add(1)
			go func() {
				defer wg.Done()
				if err := worker.runCycle(t, ctMU, ctB); err != nil {
					errCh <- err
				}
			}()
		}
		wg.Wait()
		close(errCh)
		for err := range errCh {
			if err != nil {
				panic(err)
			}
		}

		for j := 0; j < Nm; j++ {
			Uhat[j] = 0.0
		}

		// 3. Client side score computation
		logWMax := math.Inf(-1)
		for w, worker := range workers {
			base := w * KChunk
			for i := 0; i < KChunk; i++ {
				logW[base+i] = -chebEta * worker.sVals[i]
				if logW[base+i] > logWMax {
					logWMax = logW[base+i]
				}
			}
		}

		// Compute normalized weight and weighted sum of control samples
		var wSum float64
		for w, worker := range workers {
			base := w * KChunk
			for i := 0; i < KChunk; i++ {
				wi := math.Exp(logW[base+i] - logWMax)
				wSum += wi
				off := i * dim
				for j := 0; j < Nm; j++ {
					Uhat[j] += wi * worker.uFlat[off+j]
				}
			}
		}
		if wSum > 0 {
			for j := 0; j < Nm; j++ {
				Uhat[j] /= wSum
			}
		}

		for j := 0; j < mIn; j++ {
			us.Set(t, j, Uhat[j])
		}

		// 4. Client side dynamics propagation
		Ax := core.MatVecMul(A, x)
		Bu := core.MatVecMul(B, Uhat[:mIn])
		for i := 0; i < n; i++ {
			x[i] = Ax[i] + Bu[i]
			xs.Set(t+1, i, x[i])
		}

		controlMs := time.Since(iterStart).Seconds() * 1000.0
		controlMsSeries[t] = controlMs
		bar.Update(t + 1)
	}

	controlMean, controlStd := meanStd(controlMsSeries)
	fmt.Printf("Control iteration time mean/std: %.3f ms / %.3f ms\n", controlMean, controlStd)

	outDir := filepath.Join("output")
	_ = os.MkdirAll(outDir, 0o755)
	writeMatCSV(filepath.Join(outDir, "xs_ckks.csv"), xs)
	writeMatCSV(filepath.Join(outDir, "us_ckks.csv"), us)
	writeSeriesCSV(filepath.Join(outDir, "control_iter_ms_ckks.csv"), controlMsSeries)
	fmt.Printf("Saved CKKS MPC outputs to %s\n", outDir)
}
